# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oneapp', '0002_auto_20190627_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('sfirst_name', models.CharField(max_length=255)),
                ('slast_name', models.CharField(max_length=255)),
                ('saddress', models.CharField(max_length=255)),
                ('saddress2', models.CharField(default='', max_length=255)),
                ('scity', models.CharField(max_length=255)),
                ('sstate', models.CharField(max_length=40)),
                ('szipcode', models.CharField(max_length=55)),
                ('bfirst_name', models.CharField(default='', max_length=255)),
                ('blast_name', models.CharField(default='', max_length=255)),
                ('baddress', models.CharField(default='', max_length=255)),
                ('baddress2', models.CharField(default='', max_length=255)),
                ('bcity', models.CharField(default='', max_length=255)),
                ('bstate', models.CharField(default='', max_length=40)),
                ('bzipcode', models.CharField(default='', max_length=55)),
                ('card', models.CharField(max_length=55)),
                ('security', models.CharField(max_length=55)),
                ('expiration', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventory', models.IntegerField(default=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(related_name='products_included', to='oneapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='the_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_list', to='oneapp.Sport'),
        ),
    ]
