# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0003_auto_20190627_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
